export const countries = [
  "Afghanistan",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Bahamas, The",
  "Bangladesh",
  "Belgium",
  "Belize",
  "Bhutan",
  "Bosnia and Herzegovina",
  "Brazil",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Congo, Democratic Republic of the",
  "Costa Rica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "France",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Haiti",
  "Hong Kong SAR",
  "Hungary",
  "India",
  "Indonesia",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kosovo",
  "Lebanon",
  "Liberia",
  "Lithuania",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Mexico",
  "Moldova, Republic of",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Nicaragua",
  "Nigeria",
  "Pakistan",
  "Palestine",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Puerto Rico",
  "Romania",
  "Rwanda",
  "Saint Lucia",
  "Senegal",
  "Serbia",
  "Sierra Leone",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Turkey",
  "TW",
  "Uganda",
  "Ukraine",
  "United Kingdom",
  "United States",
  "Venezuela",
  "Vietnam",
  "Virgin Islands",
  "Zambia",
  "Zimbabwe",
];
